version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: documind-postgres
    environment:
      POSTGRES_DB: documind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: documind-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@documind.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
